name: publish release

on:
  push:
    tags:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Run tests
        run: npm run test

      - name: Build
        run: npm run build

      # Reuse tag build
      - name: Cache build dir
        uses: actions/cache@v2
        id: build-cache
        with:
          path: dist
          key: ${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ github.sha }}

      - name: Install and Build ğŸ”§
        if: steps.build-cache.outputs.cache-hit != 'true'
        run: |
          npm ci --prefer-offline --no-audit --progress=false --cache ${{ github.workspace }}/.cache/npm
          npm run build

      - name: Create archive
        run: tar -czf saturn-l2-webui.tar.gz dist/*

      - name: Attach prebuilt archive to Release Notes
        uses: skx/github-action-publish-binaries@c881a3f8ffb80b684f367660178d38ceabc065c2 #release-0.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "./saturn-l2-webui.tar.gz"
